name: Samsungknox-token-library CI
on:
  pull_request:
    paths:
      - packages/knox-token-library/**

jobs:
  everything:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Init Doppler Token
        uses: dopplerhq/secrets-fetch-action@v1.1.0
        id: doppler-token
        with:
          doppler-token: ${{ secrets.SAMSUNGKNOX_TOKEN_LIBRARY_DOPPLER_TOKEN }}
          inject-env-vars: false

      - name: Install dependencies
        run: pnpm i

      - name: Lint Format
        working-directory: packages/knox-token-library
        run: pnpm lint:format

      - name: Type Check
        working-directory: packages/knox-token-library
        run: pnpm type-check

      - name: Test
        working-directory: packages/knox-token-library
        run: pnpm test
        env: 
          JWT_TOKEN_KEY: ${{ steps.doppler-token.outputs.JWT_TOKEN_KEY }}
          CREDENTIAL_TEST_KEY:  ${{ steps.doppler-token.outputs.CREDENTIAL_TEST_KEY }}

      - name: Build
        working-directory: packages/knox-token-library
        run: pnpm build

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true