name: Samsungknox-Docs Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/knox-docs/CHANGELOG.md'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Use Node.js 24.13.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        working-directory: packages/knox-docs
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/knox-docs/out
