name: Samsungknox-token-library Pakcage Publish

on:
  push:
    branches:
      - main
    paths:
      - 'packages/knox-token-library/CHANGELOG.md'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Use Node.js 24.13.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Format
        working-directory: packages/knox-token-library
        run: pnpm lint:format

      - name: Type Check
        working-directory: packages/knox-token-library
        run: pnpm type-check

      - name: Test
        working-directory: packages/knox-token-library
        run: pnpm test

      - name: Build
        working-directory: packages/knox-token-library
        run: pnpm build:production

      - name: Publish to npm
        working-directory: packages/knox-token-library
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_ACCESS_TOKEN}}
