name: Samsungknox-token-library Pakcage Publish

on:
  push:
    branches:
      - master
    tags:
      - 'knox-token-library@*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/knox-token-library@')
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm i

      - name: Lint Format
        working-directory: packages/knox-token-library
        run: pnpm lint:format

      - name: Type Check
        working-directory: packages/knox-token-library
        run: pnpm type-check

      - name: Test
        working-directory: packages/knox-token-library
        run: pnpm test

      - name: Build
        working-directory: packages/knox-token-library
        run: pnpm build:production

      - name: Publish to npm
        working-directory: packages/knox-token-library
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_ACCESS_TOKEN}}