name: Samsungknox-fastlane Gems Publish

on:
  push:
    branches:
      - main
    paths:
      - 'packages/knox-fastlane-plugin/CHANGELOG.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
        bundler-cache: true
        working-directory: packages/knox-fastlane-plugin

    - name: Install dependencies
      working-directory: packages/knox-fastlane-plugin
      run: bundle install

    - name: Rake install
      working-directory: packages/knox-fastlane-plugin
      run: bundle exec rake install

    - name: Release Gem
      working-directory: packages/knox-fastlane-plugin
      run: bundle exec rake release
      env:
        RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
