name: Samsungknox-api Pakcage Publish

on:
  push:
    branches:
      - master
    paths:
      - 'packages/knox-api/CHANGELOG.md'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm i

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
  
      - name: Export .env
        working-directory: packages/knox-api
        run: doppler secrets download --no-file --format env-no-quotes > .env
        env: 
          DOPPLER_TOKEN: ${{ secrets.TEST_DOPPLER_TOKEN }}

      - name: Lint Format
        working-directory: packages/knox-api
        run: pnpm lint:format

      - name: Build Knox-Token-Library
        working-directory: packages/knox-token-library
        run: pnpm build:production

      - name: Type Check
        working-directory: packages/knox-api
        run: pnpm type-check

      - name: Test
        working-directory: packages/knox-api
        run: pnpm test

      - name: Remove .env
        working-directory: packages/knox-api
        run: rm -R .env

      - name: Build
        working-directory: packages/knox-api
        run: pnpm build:production

      - name: Publish to npm
        working-directory: packages/knox-api
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_ACCESS_TOKEN}}