name: Sync Changeset Version

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 20000
          fetch-tags: true

      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Use Node.js 24.13.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create or Update Release Pull Request
        uses: ./scripts/src/changeset
        with: 
          log-level: action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0'
